settings:
  APP_DISPLAY_NAME: Feral
  PRODUCTION_APP_NAME: Feral
  APP_GROUP_IDENTIFIER: group.io.feral
  BASE_BUNDLE_IDENTIFIER: io.feral.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: ${FERAL_DEVELOPMENT_TEAM:-}
